---
swappiness_value: 1
current_date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
redhat_packages:
  - ntp
  - unzip
  - deltarpm
  - epel-release
  - libselinux-python
  - postgresql-jdbc
  - lzo

ipables_commands:
  - iptables -F
  - iptables -X
  - iptables -t nat -F
  - iptables -t nat -X
  - iptables -t mangle -F
  - iptables -t mangle -X
  - iptables -P INPUT ACCEPT
  - iptables -P OUTPUT ACCEPT
  - iptables -P FORWARD ACCEPT

tune_kernel:
  netdev_max_backlog:
    name: 'net.core.netdev_max_backlog'
    value: '250000'
  optmem_max:
    name: net.core.optmem_max
    value: 4194304s
  rmem_default:
    name: net.core.rmem_default
    value: 4194304
  rmem_max:
    name: net.core.rmem_max
    value: 4194304
  wmem_default:
    name: net.core.wmem_default
    value: 4194304
  wmem_max:
    name: net.core.wmem_max
    value: 4194304
  tcp_adv_win_scale:
    name: net.ipv4.tcp_adv_win_scale
    value: 1
  tcp_low_latency:
    name: net.ipv4.tcp_low_latency
    value: 1
  tcp_sack:
    name: net.ipv4.tcp_sack
    value: 1
  tcp_timestamps:
    name: net.ipv4.tcp_timestamps
    value: 0
  tcp_rmem:
    name: net.ipv4.tcp_rmem
    value: '4096 87380 4194304'
  tcp_wmem:
    name: net.ipv4.tcp_wmem
    value: '4096 65536 4194304'

usehaveged: false


